work_dir: ./work_dir/recognition_gat/ntu-xsub/gat_tcn

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: /home/hqu/st-gcn/data/NTU-RGB-D/xsub/train_data.npy
  label_path: /home/hqu/st-gcn/data/NTU-RGB-D/xsub/train_label.pkl
test_feeder_args:
  data_path: /home/hqu/st-gcn/data/NTU-RGB-D/xsub/val_data.npy
  label_path: /home/hqu/st-gcn/data/NTU-RGB-D/xsub/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
#  edge_importance_weighting: True
  edge_importance_weighting: false
  graph_args:
    layout: 'ntu-rgb+d'
#    strategy: 'spatial'
    strategy: 'uniform'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [0]
batch_size: 10
test_batch_size: 10
num_epoch: 10



